### ISSUE TITLE
Android 4.4.4, Chrome 33.0.0, RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by littlee** [goldfire/howler.js#1202]
my code:
```js
const bgm = new Howl({
  src: require('./assets/gg.mp3'),
  loop: true
});

bgm.play();
```

the Readme said that it can be compatible with following browsers:
> Browser Compatibility
Tested in the following browsers/versions:
Google Chrome 7.0+
Internet Explorer 9.0+
Firefox 4.0+
Safari 5.1.4+
Mobile Safari 6.0+ (after user input)
Opera 12.0+
Microsoft Edge

But I receive this error on Android 4.4.4 device with Chrome 33.0.0

```
RangeError: Maximum call stack size exceeded
  at Object.a._loadQueue(/apg-great-china-four-h5/static/js/2.24fe0520.chunk.js)
  at _emit(../node_modules/howler/dist/howler.js:1867:1)
  at _ended(../node_modules/howler/dist/howler.js:1918:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at play(../node_modules/howler/dist/howler.js:809:1)
  at _ended(../node_modules/howler/dist/howler.js:1922:1)
  at Object.a.play(../node_modules/howler/dist/howler.js:809:1)
```

sentry screenshot

<img width="869" alt="WX20190724-114112@2x" src="https://user-images.githubusercontent.com/7534668/61763443-00ecc880-ae08-11e9-8bc2-dcfad35525bb.png">

**Comment by Ekuju** [comment]
I also have this issue. To reproduce: try to play without first "unlocking" the browser, and then wait for a good bit of time, then click the browser to unlock it and begin playing.

It seems like the library is using some recursion thing to re-attempt playing to compensate for the unlock event which is overflowing.

**Comment by Ekuju** [comment]
This seems pretty high priority. It reproduces on any devices I've found that uses chrome, iOS, android, windows, mac.

If you try to play a sound upon website load, and the user doesn't interact with your website for ~15 seconds, they're *guaranteed* to crash due to this bug.

**Comment by ErikSom** [comment]
I've also seen this happen several times.

**Comment by Beeblerox** [comment]
currently, my workaround is to wait till user click on my game html-element

**Comment by amlinux** [comment]
Same here.

![image](https://user-images.githubusercontent.com/449322/112595322-8ceb9a80-8e0a-11eb-8bdb-8bb740b5d7d4.png)

**Comment by kahoot-karl** [comment]
This happens to our users on a daily basis. About 10 reports a day with various browsers including latest Chrome.

**Comment by Lumethys** [comment]
is there any solution/ workaround for this issue? Or possibly what cause it?

**Comment by barisyild** [comment]
![image](https://github.com/goldfire/howler.js/assets/25794892/d2da3c45-1855-4193-b99c-b6c606bc5a64)
I am experiencing an error like in the image.

**Comment by jamespohalloran** [comment]
Anyone found a workaround for this yet? Seems like a pretty significant issue

**Comment by jamespohalloran** [comment]
Alright I think I have a workaround for my issue at least!
I was updating the volume for a Howl on every frame. When the window was inactive, and I eventually came back to it, things blew up. I'm not sure if this was a recursive issue, but sounds like not.  

My fix was to add some checks at the app-level to avoid stacking too many volume events. If this is the issue for others seeing this error, maybe a the fix may be to log a warning if too many volume (or other events) are stacked up?
