### ISSUE TITLE
var testPlay = new Audio().play(); ReferenceError: Audio is not defined

### ISSUE THREAD

**Issue by VirtualMirai** [goldfire/howler.js#1260]
I used the most basic example but I have not gotten this module to work:

`const {Howl, Howler} = require('howler');
// const electron = require('electron');
// const {dialog} = require('electron')
var sound = new Howl({
			  src: ['music.mp3'],
		  	  format: ['mp3']
		  });

sound.play();`

Results in:

`node temp.js
C:\Users\MiraiM\eclipse-workspace\Player\node_modules\howler\dist\howler.js:409
      var testPlay = new Audio().play();
                     ^

ReferenceError: Audio is not defined
    at HowlerGlobal._obtainHtml5Audio (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:409:22)
    at Sound.create (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:2207:29)
    at Sound.init (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:2185:12)
    at Sound.init (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:3063:14)
    at new Sound (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:2157:10)
    at Howl._inactiveSound (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:2022:14)
    at Howl.play (C:\Users\MiraiM\eclipse-workspace\Player\node_modules\[4mhowler[24m\dist\howler.js:744:51)
    at Object.<anonymous> (C:\Users\MiraiM\eclipse-workspace\Player\temp.js:9:7)
[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m`

Version of Howler: 2.1.2

**Comment by VirtualMirai** [comment]
Looks to me it is because it cannot use audio in console. A little shame, but made a work around by using the "step" function to push updates to the back end.

**Comment by jellohouse** [comment]
I'm having some issues with Electron as well https://github.com/goldfire/howler.js/issues/1467

What do you mean by "it cannot use audio in console"?

**Comment by VirtualMirai** [comment]
The issue is not related to electron but by NodeJS itself, this needs Electron with GUI. I was running it from NodeJS itself.
